//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaniAPIsHandler.PWServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reponse", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class reponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsecodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tranidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionvnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string macField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string deviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string environmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cardSchemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enable3DSecureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datakeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string napaskeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string responsecode {
            get {
                return this.responsecodeField;
            }
            set {
                if ((object.ReferenceEquals(this.responsecodeField, value) != true)) {
                    this.responsecodeField = value;
                    this.RaisePropertyChanged("responsecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tranid {
            get {
                return this.tranidField;
            }
            set {
                if ((object.ReferenceEquals(this.tranidField, value) != true)) {
                    this.tranidField = value;
                    this.RaisePropertyChanged("tranid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descriptionvn {
            get {
                return this.descriptionvnField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionvnField, value) != true)) {
                    this.descriptionvnField = value;
                    this.RaisePropertyChanged("descriptionvn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string descriptionen {
            get {
                return this.descriptionenField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionenField, value) != true)) {
                    this.descriptionenField = value;
                    this.RaisePropertyChanged("descriptionen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mac {
            get {
                return this.macField;
            }
            set {
                if ((object.ReferenceEquals(this.macField, value) != true)) {
                    this.macField = value;
                    this.RaisePropertyChanged("mac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string merchantId {
            get {
                return this.merchantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantIdField, value) != true)) {
                    this.merchantIdField = value;
                    this.RaisePropertyChanged("merchantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string clientIP {
            get {
                return this.clientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.clientIPField, value) != true)) {
                    this.clientIPField = value;
                    this.RaisePropertyChanged("clientIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.deviceIdField, value) != true)) {
                    this.deviceIdField = value;
                    this.RaisePropertyChanged("deviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string environment {
            get {
                return this.environmentField;
            }
            set {
                if ((object.ReferenceEquals(this.environmentField, value) != true)) {
                    this.environmentField = value;
                    this.RaisePropertyChanged("environment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string cardScheme {
            get {
                return this.cardSchemeField;
            }
            set {
                if ((object.ReferenceEquals(this.cardSchemeField, value) != true)) {
                    this.cardSchemeField = value;
                    this.RaisePropertyChanged("cardScheme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string enable3DSecure {
            get {
                return this.enable3DSecureField;
            }
            set {
                if ((object.ReferenceEquals(this.enable3DSecureField, value) != true)) {
                    this.enable3DSecureField = value;
                    this.RaisePropertyChanged("enable3DSecure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string datakey {
            get {
                return this.datakeyField;
            }
            set {
                if ((object.ReferenceEquals(this.datakeyField, value) != true)) {
                    this.datakeyField = value;
                    this.RaisePropertyChanged("datakey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string napaskey {
            get {
                return this.napaskeyField;
            }
            set {
                if ((object.ReferenceEquals(this.napaskeyField, value) != true)) {
                    this.napaskeyField = value;
                    this.RaisePropertyChanged("napaskey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PWServices.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name merchantid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Payment", ReplyAction="*")]
        VaniAPIsHandler.PWServices.PaymentResponse Payment(VaniAPIsHandler.PWServices.PaymentRequest request);
        
        // CODEGEN: Generating message contract since element name merchantid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentNapasV3", ReplyAction="*")]
        VaniAPIsHandler.PWServices.PaymentNapasV3Response PaymentNapasV3(VaniAPIsHandler.PWServices.PaymentNapasV3Request request);
        
        // CODEGEN: Generating message contract since element name merchantcode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comfirmPayment", ReplyAction="*")]
        VaniAPIsHandler.PWServices.comfirmPaymentResponse comfirmPayment(VaniAPIsHandler.PWServices.comfirmPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name tranid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPaymentStatus", ReplyAction="*")]
        VaniAPIsHandler.PWServices.getPaymentStatusResponse getPaymentStatus(VaniAPIsHandler.PWServices.getPaymentStatusRequest request);
        
        // CODEGEN: Generating message contract since element name merchantid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/paymentVisaMaster", ReplyAction="*")]
        VaniAPIsHandler.PWServices.paymentVisaMasterResponse paymentVisaMaster(VaniAPIsHandler.PWServices.paymentVisaMasterRequest request);
        
        // CODEGEN: Generating message contract since element name merchantid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/paymentVisaMasterVer2", ReplyAction="*")]
        VaniAPIsHandler.PWServices.paymentVisaMasterVer2Response paymentVisaMasterVer2(VaniAPIsHandler.PWServices.paymentVisaMasterVer2Request request);
        
        // CODEGEN: Generating message contract since element name getCardNumberByTransactionIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCardNumberByTransactionId", ReplyAction="*")]
        VaniAPIsHandler.PWServices.getCardNumberByTransactionIdResponse getCardNumberByTransactionId(VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Payment", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.PaymentRequestBody Body;
        
        public PaymentRequest() {
        }
        
        public PaymentRequest(VaniAPIsHandler.PWServices.PaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string termtxndatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txnAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IssuerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string tranID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string bankID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string respUrl;
        
        public PaymentRequestBody() {
        }
        
        public PaymentRequestBody(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, string bankID, string mac, string respUrl) {
            this.merchantid = merchantid;
            this.stan = stan;
            this.termtxndatetime = termtxndatetime;
            this.txnAmount = txnAmount;
            this.fee = fee;
            this.userName = userName;
            this.IssuerID = IssuerID;
            this.tranID = tranID;
            this.bankID = bankID;
            this.mac = mac;
            this.respUrl = respUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.PaymentResponseBody Body;
        
        public PaymentResponse() {
        }
        
        public PaymentResponse(VaniAPIsHandler.PWServices.PaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VaniAPIsHandler.PWServices.reponse PaymentResult;
        
        public PaymentResponseBody() {
        }
        
        public PaymentResponseBody(VaniAPIsHandler.PWServices.reponse PaymentResult) {
            this.PaymentResult = PaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentNapasV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentNapasV3", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.PaymentNapasV3RequestBody Body;
        
        public PaymentNapasV3Request() {
        }
        
        public PaymentNapasV3Request(VaniAPIsHandler.PWServices.PaymentNapasV3RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentNapasV3RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string termtxndatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txnAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IssuerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string tranID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool useToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string bankID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string respUrl;
        
        public PaymentNapasV3RequestBody() {
        }
        
        public PaymentNapasV3RequestBody(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, bool useToken, string token, string bankID, string mac, string respUrl) {
            this.merchantid = merchantid;
            this.stan = stan;
            this.termtxndatetime = termtxndatetime;
            this.txnAmount = txnAmount;
            this.fee = fee;
            this.userName = userName;
            this.IssuerID = IssuerID;
            this.tranID = tranID;
            this.useToken = useToken;
            this.token = token;
            this.bankID = bankID;
            this.mac = mac;
            this.respUrl = respUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentNapasV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentNapasV3Response", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.PaymentNapasV3ResponseBody Body;
        
        public PaymentNapasV3Response() {
        }
        
        public PaymentNapasV3Response(VaniAPIsHandler.PWServices.PaymentNapasV3ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentNapasV3ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VaniAPIsHandler.PWServices.reponse PaymentNapasV3Result;
        
        public PaymentNapasV3ResponseBody() {
        }
        
        public PaymentNapasV3ResponseBody(VaniAPIsHandler.PWServices.reponse PaymentNapasV3Result) {
            this.PaymentNapasV3Result = PaymentNapasV3Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comfirmPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comfirmPayment", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.comfirmPaymentRequestBody Body;
        
        public comfirmPaymentRequest() {
        }
        
        public comfirmPaymentRequest(VaniAPIsHandler.PWServices.comfirmPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comfirmPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tranid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string txnAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string confirmCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mackey;
        
        public comfirmPaymentRequestBody() {
        }
        
        public comfirmPaymentRequestBody(string merchantcode, string tranid, string txnAmount, string confirmCode, string mackey) {
            this.merchantcode = merchantcode;
            this.tranid = tranid;
            this.txnAmount = txnAmount;
            this.confirmCode = confirmCode;
            this.mackey = mackey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comfirmPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comfirmPaymentResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.comfirmPaymentResponseBody Body;
        
        public comfirmPaymentResponse() {
        }
        
        public comfirmPaymentResponse(VaniAPIsHandler.PWServices.comfirmPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class comfirmPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VaniAPIsHandler.PWServices.reponse comfirmPaymentResult;
        
        public comfirmPaymentResponseBody() {
        }
        
        public comfirmPaymentResponseBody(VaniAPIsHandler.PWServices.reponse comfirmPaymentResult) {
            this.comfirmPaymentResult = comfirmPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentStatus", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.getPaymentStatusRequestBody Body;
        
        public getPaymentStatusRequest() {
        }
        
        public getPaymentStatusRequest(VaniAPIsHandler.PWServices.getPaymentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPaymentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tranid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mackey;
        
        public getPaymentStatusRequestBody() {
        }
        
        public getPaymentStatusRequestBody(string tranid, string merchantcode, string mackey) {
            this.tranid = tranid;
            this.merchantcode = merchantcode;
            this.mackey = mackey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPaymentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPaymentStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.getPaymentStatusResponseBody Body;
        
        public getPaymentStatusResponse() {
        }
        
        public getPaymentStatusResponse(VaniAPIsHandler.PWServices.getPaymentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPaymentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VaniAPIsHandler.PWServices.reponse getPaymentStatusResult;
        
        public getPaymentStatusResponseBody() {
        }
        
        public getPaymentStatusResponseBody(VaniAPIsHandler.PWServices.reponse getPaymentStatusResult) {
            this.getPaymentStatusResult = getPaymentStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentVisaMasterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentVisaMaster", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.paymentVisaMasterRequestBody Body;
        
        public paymentVisaMasterRequest() {
        }
        
        public paymentVisaMasterRequest(VaniAPIsHandler.PWServices.paymentVisaMasterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentVisaMasterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string termtxndatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txnAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cusEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string tranNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string IssuerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string tranID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string bankID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string respUrl;
        
        public paymentVisaMasterRequestBody() {
        }
        
        public paymentVisaMasterRequestBody(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string firstName, string lastName, string cusEmail, string tranNote, string IssuerID, string tranID, string bankID, string mac, string respUrl) {
            this.merchantid = merchantid;
            this.stan = stan;
            this.termtxndatetime = termtxndatetime;
            this.txnAmount = txnAmount;
            this.fee = fee;
            this.userName = userName;
            this.firstName = firstName;
            this.lastName = lastName;
            this.cusEmail = cusEmail;
            this.tranNote = tranNote;
            this.IssuerID = IssuerID;
            this.tranID = tranID;
            this.bankID = bankID;
            this.mac = mac;
            this.respUrl = respUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentVisaMasterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentVisaMasterResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.paymentVisaMasterResponseBody Body;
        
        public paymentVisaMasterResponse() {
        }
        
        public paymentVisaMasterResponse(VaniAPIsHandler.PWServices.paymentVisaMasterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentVisaMasterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VaniAPIsHandler.PWServices.reponse paymentVisaMasterResult;
        
        public paymentVisaMasterResponseBody() {
        }
        
        public paymentVisaMasterResponseBody(VaniAPIsHandler.PWServices.reponse paymentVisaMasterResult) {
            this.paymentVisaMasterResult = paymentVisaMasterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentVisaMasterVer2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentVisaMasterVer2", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.paymentVisaMasterVer2RequestBody Body;
        
        public paymentVisaMasterVer2Request() {
        }
        
        public paymentVisaMasterVer2Request(VaniAPIsHandler.PWServices.paymentVisaMasterVer2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentVisaMasterVer2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string merchantid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string termtxndatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string txnAmount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string fee;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string currency;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cusEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string tranNote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string IssuerID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string tranID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string bankID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string mac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string respUrl;
        
        public paymentVisaMasterVer2RequestBody() {
        }
        
        public paymentVisaMasterVer2RequestBody(
                    string merchantid, 
                    string stan, 
                    string termtxndatetime, 
                    string txnAmount, 
                    string fee, 
                    string currency, 
                    string userName, 
                    string firstName, 
                    string lastName, 
                    string cusEmail, 
                    string tranNote, 
                    string IssuerID, 
                    string tranID, 
                    string bankID, 
                    string mac, 
                    string respUrl) {
            this.merchantid = merchantid;
            this.stan = stan;
            this.termtxndatetime = termtxndatetime;
            this.txnAmount = txnAmount;
            this.fee = fee;
            this.currency = currency;
            this.userName = userName;
            this.firstName = firstName;
            this.lastName = lastName;
            this.cusEmail = cusEmail;
            this.tranNote = tranNote;
            this.IssuerID = IssuerID;
            this.tranID = tranID;
            this.bankID = bankID;
            this.mac = mac;
            this.respUrl = respUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class paymentVisaMasterVer2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="paymentVisaMasterVer2Response", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.paymentVisaMasterVer2ResponseBody Body;
        
        public paymentVisaMasterVer2Response() {
        }
        
        public paymentVisaMasterVer2Response(VaniAPIsHandler.PWServices.paymentVisaMasterVer2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class paymentVisaMasterVer2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VaniAPIsHandler.PWServices.reponse paymentVisaMasterVer2Result;
        
        public paymentVisaMasterVer2ResponseBody() {
        }
        
        public paymentVisaMasterVer2ResponseBody(VaniAPIsHandler.PWServices.reponse paymentVisaMasterVer2Result) {
            this.paymentVisaMasterVer2Result = paymentVisaMasterVer2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNumberByTransactionIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNumberByTransactionId", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequestBody Body;
        
        public getCardNumberByTransactionIdRequest() {
        }
        
        public getCardNumberByTransactionIdRequest(VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCardNumberByTransactionIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int transactionId;
        
        public getCardNumberByTransactionIdRequestBody() {
        }
        
        public getCardNumberByTransactionIdRequestBody(int transactionId) {
            this.transactionId = transactionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCardNumberByTransactionIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCardNumberByTransactionIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.PWServices.getCardNumberByTransactionIdResponseBody Body;
        
        public getCardNumberByTransactionIdResponse() {
        }
        
        public getCardNumberByTransactionIdResponse(VaniAPIsHandler.PWServices.getCardNumberByTransactionIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCardNumberByTransactionIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCardNumberByTransactionIdResult;
        
        public getCardNumberByTransactionIdResponseBody() {
        }
        
        public getCardNumberByTransactionIdResponseBody(string getCardNumberByTransactionIdResult) {
            this.getCardNumberByTransactionIdResult = getCardNumberByTransactionIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : VaniAPIsHandler.PWServices.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<VaniAPIsHandler.PWServices.ServiceSoap>, VaniAPIsHandler.PWServices.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.PaymentResponse VaniAPIsHandler.PWServices.ServiceSoap.Payment(VaniAPIsHandler.PWServices.PaymentRequest request) {
            return base.Channel.Payment(request);
        }
        
        public VaniAPIsHandler.PWServices.reponse Payment(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, string bankID, string mac, string respUrl) {
            VaniAPIsHandler.PWServices.PaymentRequest inValue = new VaniAPIsHandler.PWServices.PaymentRequest();
            inValue.Body = new VaniAPIsHandler.PWServices.PaymentRequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.stan = stan;
            inValue.Body.termtxndatetime = termtxndatetime;
            inValue.Body.txnAmount = txnAmount;
            inValue.Body.fee = fee;
            inValue.Body.userName = userName;
            inValue.Body.IssuerID = IssuerID;
            inValue.Body.tranID = tranID;
            inValue.Body.bankID = bankID;
            inValue.Body.mac = mac;
            inValue.Body.respUrl = respUrl;
            VaniAPIsHandler.PWServices.PaymentResponse retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).Payment(inValue);
            return retVal.Body.PaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.PaymentNapasV3Response VaniAPIsHandler.PWServices.ServiceSoap.PaymentNapasV3(VaniAPIsHandler.PWServices.PaymentNapasV3Request request) {
            return base.Channel.PaymentNapasV3(request);
        }
        
        public VaniAPIsHandler.PWServices.reponse PaymentNapasV3(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string IssuerID, string tranID, bool useToken, string token, string bankID, string mac, string respUrl) {
            VaniAPIsHandler.PWServices.PaymentNapasV3Request inValue = new VaniAPIsHandler.PWServices.PaymentNapasV3Request();
            inValue.Body = new VaniAPIsHandler.PWServices.PaymentNapasV3RequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.stan = stan;
            inValue.Body.termtxndatetime = termtxndatetime;
            inValue.Body.txnAmount = txnAmount;
            inValue.Body.fee = fee;
            inValue.Body.userName = userName;
            inValue.Body.IssuerID = IssuerID;
            inValue.Body.tranID = tranID;
            inValue.Body.useToken = useToken;
            inValue.Body.token = token;
            inValue.Body.bankID = bankID;
            inValue.Body.mac = mac;
            inValue.Body.respUrl = respUrl;
            VaniAPIsHandler.PWServices.PaymentNapasV3Response retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).PaymentNapasV3(inValue);
            return retVal.Body.PaymentNapasV3Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.comfirmPaymentResponse VaniAPIsHandler.PWServices.ServiceSoap.comfirmPayment(VaniAPIsHandler.PWServices.comfirmPaymentRequest request) {
            return base.Channel.comfirmPayment(request);
        }
        
        public VaniAPIsHandler.PWServices.reponse comfirmPayment(string merchantcode, string tranid, string txnAmount, string confirmCode, string mackey) {
            VaniAPIsHandler.PWServices.comfirmPaymentRequest inValue = new VaniAPIsHandler.PWServices.comfirmPaymentRequest();
            inValue.Body = new VaniAPIsHandler.PWServices.comfirmPaymentRequestBody();
            inValue.Body.merchantcode = merchantcode;
            inValue.Body.tranid = tranid;
            inValue.Body.txnAmount = txnAmount;
            inValue.Body.confirmCode = confirmCode;
            inValue.Body.mackey = mackey;
            VaniAPIsHandler.PWServices.comfirmPaymentResponse retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).comfirmPayment(inValue);
            return retVal.Body.comfirmPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.getPaymentStatusResponse VaniAPIsHandler.PWServices.ServiceSoap.getPaymentStatus(VaniAPIsHandler.PWServices.getPaymentStatusRequest request) {
            return base.Channel.getPaymentStatus(request);
        }
        
        public VaniAPIsHandler.PWServices.reponse getPaymentStatus(string tranid, string merchantcode, string mackey) {
            VaniAPIsHandler.PWServices.getPaymentStatusRequest inValue = new VaniAPIsHandler.PWServices.getPaymentStatusRequest();
            inValue.Body = new VaniAPIsHandler.PWServices.getPaymentStatusRequestBody();
            inValue.Body.tranid = tranid;
            inValue.Body.merchantcode = merchantcode;
            inValue.Body.mackey = mackey;
            VaniAPIsHandler.PWServices.getPaymentStatusResponse retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).getPaymentStatus(inValue);
            return retVal.Body.getPaymentStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.paymentVisaMasterResponse VaniAPIsHandler.PWServices.ServiceSoap.paymentVisaMaster(VaniAPIsHandler.PWServices.paymentVisaMasterRequest request) {
            return base.Channel.paymentVisaMaster(request);
        }
        
        public VaniAPIsHandler.PWServices.reponse paymentVisaMaster(string merchantid, string stan, string termtxndatetime, string txnAmount, string fee, string userName, string firstName, string lastName, string cusEmail, string tranNote, string IssuerID, string tranID, string bankID, string mac, string respUrl) {
            VaniAPIsHandler.PWServices.paymentVisaMasterRequest inValue = new VaniAPIsHandler.PWServices.paymentVisaMasterRequest();
            inValue.Body = new VaniAPIsHandler.PWServices.paymentVisaMasterRequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.stan = stan;
            inValue.Body.termtxndatetime = termtxndatetime;
            inValue.Body.txnAmount = txnAmount;
            inValue.Body.fee = fee;
            inValue.Body.userName = userName;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.cusEmail = cusEmail;
            inValue.Body.tranNote = tranNote;
            inValue.Body.IssuerID = IssuerID;
            inValue.Body.tranID = tranID;
            inValue.Body.bankID = bankID;
            inValue.Body.mac = mac;
            inValue.Body.respUrl = respUrl;
            VaniAPIsHandler.PWServices.paymentVisaMasterResponse retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).paymentVisaMaster(inValue);
            return retVal.Body.paymentVisaMasterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.paymentVisaMasterVer2Response VaniAPIsHandler.PWServices.ServiceSoap.paymentVisaMasterVer2(VaniAPIsHandler.PWServices.paymentVisaMasterVer2Request request) {
            return base.Channel.paymentVisaMasterVer2(request);
        }
        
        public VaniAPIsHandler.PWServices.reponse paymentVisaMasterVer2(
                    string merchantid, 
                    string stan, 
                    string termtxndatetime, 
                    string txnAmount, 
                    string fee, 
                    string currency, 
                    string userName, 
                    string firstName, 
                    string lastName, 
                    string cusEmail, 
                    string tranNote, 
                    string IssuerID, 
                    string tranID, 
                    string bankID, 
                    string mac, 
                    string respUrl) {
            VaniAPIsHandler.PWServices.paymentVisaMasterVer2Request inValue = new VaniAPIsHandler.PWServices.paymentVisaMasterVer2Request();
            inValue.Body = new VaniAPIsHandler.PWServices.paymentVisaMasterVer2RequestBody();
            inValue.Body.merchantid = merchantid;
            inValue.Body.stan = stan;
            inValue.Body.termtxndatetime = termtxndatetime;
            inValue.Body.txnAmount = txnAmount;
            inValue.Body.fee = fee;
            inValue.Body.currency = currency;
            inValue.Body.userName = userName;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.cusEmail = cusEmail;
            inValue.Body.tranNote = tranNote;
            inValue.Body.IssuerID = IssuerID;
            inValue.Body.tranID = tranID;
            inValue.Body.bankID = bankID;
            inValue.Body.mac = mac;
            inValue.Body.respUrl = respUrl;
            VaniAPIsHandler.PWServices.paymentVisaMasterVer2Response retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).paymentVisaMasterVer2(inValue);
            return retVal.Body.paymentVisaMasterVer2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.PWServices.getCardNumberByTransactionIdResponse VaniAPIsHandler.PWServices.ServiceSoap.getCardNumberByTransactionId(VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequest request) {
            return base.Channel.getCardNumberByTransactionId(request);
        }
        
        public string getCardNumberByTransactionId(int transactionId) {
            VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequest inValue = new VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequest();
            inValue.Body = new VaniAPIsHandler.PWServices.getCardNumberByTransactionIdRequestBody();
            inValue.Body.transactionId = transactionId;
            VaniAPIsHandler.PWServices.getCardNumberByTransactionIdResponse retVal = ((VaniAPIsHandler.PWServices.ServiceSoap)(this)).getCardNumberByTransactionId(inValue);
            return retVal.Body.getCardNumberByTransactionIdResult;
        }
    }
}
