//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MP.Lib.ImageService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageService.ImagesResizeSoap")]
    public interface ImagesResizeSoap {
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateAvatarManual", ReplyAction="*")]
        MP.Lib.ImageService.GenerateAvatarManualResponse GenerateAvatarManual(MP.Lib.ImageService.GenerateAvatarManualRequest request);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateAvatarThumnail", ReplyAction="*")]
        MP.Lib.ImageService.GenerateAvatarThumnailResponse GenerateAvatarThumnail(MP.Lib.ImageService.GenerateAvatarThumnailRequest request);
        
        // CODEGEN: Generating message contract since element name url from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateMobileThumnail", ReplyAction="*")]
        MP.Lib.ImageService.GenerateMobileThumnailResponse GenerateMobileThumnail(MP.Lib.ImageService.GenerateMobileThumnailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAvatarManualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAvatarManual", Namespace="http://tempuri.org/", Order=0)]
        public MP.Lib.ImageService.GenerateAvatarManualRequestBody Body;
        
        public GenerateAvatarManualRequest() {
        }
        
        public GenerateAvatarManualRequest(MP.Lib.ImageService.GenerateAvatarManualRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateAvatarManualRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int height;
        
        public GenerateAvatarManualRequestBody() {
        }
        
        public GenerateAvatarManualRequestBody(string url, int width, int height) {
            this.url = url;
            this.width = width;
            this.height = height;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAvatarManualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAvatarManualResponse", Namespace="http://tempuri.org/", Order=0)]
        public MP.Lib.ImageService.GenerateAvatarManualResponseBody Body;
        
        public GenerateAvatarManualResponse() {
        }
        
        public GenerateAvatarManualResponse(MP.Lib.ImageService.GenerateAvatarManualResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerateAvatarManualResponseBody {
        
        public GenerateAvatarManualResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAvatarThumnailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAvatarThumnail", Namespace="http://tempuri.org/", Order=0)]
        public MP.Lib.ImageService.GenerateAvatarThumnailRequestBody Body;
        
        public GenerateAvatarThumnailRequest() {
        }
        
        public GenerateAvatarThumnailRequest(MP.Lib.ImageService.GenerateAvatarThumnailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateAvatarThumnailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int height;
        
        public GenerateAvatarThumnailRequestBody() {
        }
        
        public GenerateAvatarThumnailRequestBody(string url, int width, int height) {
            this.url = url;
            this.width = width;
            this.height = height;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateAvatarThumnailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateAvatarThumnailResponse", Namespace="http://tempuri.org/", Order=0)]
        public MP.Lib.ImageService.GenerateAvatarThumnailResponseBody Body;
        
        public GenerateAvatarThumnailResponse() {
        }
        
        public GenerateAvatarThumnailResponse(MP.Lib.ImageService.GenerateAvatarThumnailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerateAvatarThumnailResponseBody {
        
        public GenerateAvatarThumnailResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateMobileThumnailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateMobileThumnail", Namespace="http://tempuri.org/", Order=0)]
        public MP.Lib.ImageService.GenerateMobileThumnailRequestBody Body;
        
        public GenerateMobileThumnailRequest() {
        }
        
        public GenerateMobileThumnailRequest(MP.Lib.ImageService.GenerateMobileThumnailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateMobileThumnailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public GenerateMobileThumnailRequestBody() {
        }
        
        public GenerateMobileThumnailRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateMobileThumnailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateMobileThumnailResponse", Namespace="http://tempuri.org/", Order=0)]
        public MP.Lib.ImageService.GenerateMobileThumnailResponseBody Body;
        
        public GenerateMobileThumnailResponse() {
        }
        
        public GenerateMobileThumnailResponse(MP.Lib.ImageService.GenerateMobileThumnailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerateMobileThumnailResponseBody {
        
        public GenerateMobileThumnailResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImagesResizeSoapChannel : MP.Lib.ImageService.ImagesResizeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImagesResizeSoapClient : System.ServiceModel.ClientBase<MP.Lib.ImageService.ImagesResizeSoap>, MP.Lib.ImageService.ImagesResizeSoap {
        
        public ImagesResizeSoapClient() {
        }
        
        public ImagesResizeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImagesResizeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImagesResizeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImagesResizeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MP.Lib.ImageService.GenerateAvatarManualResponse MP.Lib.ImageService.ImagesResizeSoap.GenerateAvatarManual(MP.Lib.ImageService.GenerateAvatarManualRequest request) {
            return base.Channel.GenerateAvatarManual(request);
        }
        
        public void GenerateAvatarManual(string url, int width, int height) {
            MP.Lib.ImageService.GenerateAvatarManualRequest inValue = new MP.Lib.ImageService.GenerateAvatarManualRequest();
            inValue.Body = new MP.Lib.ImageService.GenerateAvatarManualRequestBody();
            inValue.Body.url = url;
            inValue.Body.width = width;
            inValue.Body.height = height;
            MP.Lib.ImageService.GenerateAvatarManualResponse retVal = ((MP.Lib.ImageService.ImagesResizeSoap)(this)).GenerateAvatarManual(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MP.Lib.ImageService.GenerateAvatarThumnailResponse MP.Lib.ImageService.ImagesResizeSoap.GenerateAvatarThumnail(MP.Lib.ImageService.GenerateAvatarThumnailRequest request) {
            return base.Channel.GenerateAvatarThumnail(request);
        }
        
        public void GenerateAvatarThumnail(string url, int width, int height) {
            MP.Lib.ImageService.GenerateAvatarThumnailRequest inValue = new MP.Lib.ImageService.GenerateAvatarThumnailRequest();
            inValue.Body = new MP.Lib.ImageService.GenerateAvatarThumnailRequestBody();
            inValue.Body.url = url;
            inValue.Body.width = width;
            inValue.Body.height = height;
            MP.Lib.ImageService.GenerateAvatarThumnailResponse retVal = ((MP.Lib.ImageService.ImagesResizeSoap)(this)).GenerateAvatarThumnail(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MP.Lib.ImageService.GenerateMobileThumnailResponse MP.Lib.ImageService.ImagesResizeSoap.GenerateMobileThumnail(MP.Lib.ImageService.GenerateMobileThumnailRequest request) {
            return base.Channel.GenerateMobileThumnail(request);
        }
        
        public void GenerateMobileThumnail(string url) {
            MP.Lib.ImageService.GenerateMobileThumnailRequest inValue = new MP.Lib.ImageService.GenerateMobileThumnailRequest();
            inValue.Body = new MP.Lib.ImageService.GenerateMobileThumnailRequestBody();
            inValue.Body.url = url;
            MP.Lib.ImageService.GenerateMobileThumnailResponse retVal = ((MP.Lib.ImageService.ImagesResizeSoap)(this)).GenerateMobileThumnail(inValue);
        }
    }
}
