//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaniAPIsHandler.SendMailAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SendMailAPI.SendSMTPMailWSSoap")]
    public interface SendSMTPMailWSSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSendSmtpMail", ReplyAction="*")]
        VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailResponse MultiSendSmtpMail(VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSendSmtpMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSendSmtpMail", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequestBody Body;
        
        public MultiSendSmtpMailRequest() {
        }
        
        public MultiSendSmtpMailRequest(VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSendSmtpMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fromEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string subject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string content;
        
        public MultiSendSmtpMailRequestBody() {
        }
        
        public MultiSendSmtpMailRequestBody(string user, string pass, string fromEmail, string to, string subject, string content) {
            this.user = user;
            this.pass = pass;
            this.fromEmail = fromEmail;
            this.to = to;
            this.subject = subject;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSendSmtpMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSendSmtpMailResponse", Namespace="http://tempuri.org/", Order=0)]
        public VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailResponseBody Body;
        
        public MultiSendSmtpMailResponse() {
        }
        
        public MultiSendSmtpMailResponse(VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSendSmtpMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MultiSendSmtpMailResult;
        
        public MultiSendSmtpMailResponseBody() {
        }
        
        public MultiSendSmtpMailResponseBody(bool MultiSendSmtpMailResult) {
            this.MultiSendSmtpMailResult = MultiSendSmtpMailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMTPMailWSSoapChannel : VaniAPIsHandler.SendMailAPI.SendSMTPMailWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMTPMailWSSoapClient : System.ServiceModel.ClientBase<VaniAPIsHandler.SendMailAPI.SendSMTPMailWSSoap>, VaniAPIsHandler.SendMailAPI.SendSMTPMailWSSoap {
        
        public SendSMTPMailWSSoapClient() {
        }
        
        public SendSMTPMailWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMTPMailWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMTPMailWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMTPMailWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailResponse VaniAPIsHandler.SendMailAPI.SendSMTPMailWSSoap.MultiSendSmtpMail(VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequest request) {
            return base.Channel.MultiSendSmtpMail(request);
        }
        
        public bool MultiSendSmtpMail(string user, string pass, string fromEmail, string to, string subject, string content) {
            VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequest inValue = new VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequest();
            inValue.Body = new VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.fromEmail = fromEmail;
            inValue.Body.to = to;
            inValue.Body.subject = subject;
            inValue.Body.content = content;
            VaniAPIsHandler.SendMailAPI.MultiSendSmtpMailResponse retVal = ((VaniAPIsHandler.SendMailAPI.SendSMTPMailWSSoap)(this)).MultiSendSmtpMail(inValue);
            return retVal.Body.MultiSendSmtpMailResult;
        }
    }
}
