//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaniAPIsHandler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VaniAPIsHandler.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam on ban da dat phong tai Dealtoday.vn. Ma DH:{0}. Ma dat phong se duoc gui toi ban ngay khi don hang duoc xac nhan. LH: 19002065.
        /// </summary>
        internal static string Booking_CompleteSMS {
            get {
                return ResourceManager.GetString("Booking_CompleteSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam on ban da dat phong tai Dealtoday.vn. Ma DH:{0}, Dealtoday se tien hanh xac nhan va dat phong giup ban. LH: 19002065.
        /// </summary>
        internal static string D2DSupportBookingSMS {
            get {
                return ResourceManager.GetString("D2DSupportBookingSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width: 100%; background: #fff; margin: 0 auto&quot;&gt;
        ///        &lt;table style=&quot;background: #F58220; padding: 5px 0; width: 100%;&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td style=&quot;text-align: center;&quot;&gt;
        ///                    &lt;b style=&quot;color: #fff;&quot;&gt;&lt;a style=&quot;color: #fff;&quot; href=&quot;www.dealtoday.vn&quot;&gt;www.dealtoday.vn&lt;/a&gt;&lt;/b&gt;
        ///                &lt;/td&gt;
        ///                &lt;td style=&quot;text-align: center;&quot;&gt;
        ///                    &lt;b style=&quot;color: #fff;&quot;&gt;Hotline: 1900 2065&lt;/b&gt;
        ///                &lt;/td&gt;
        ///            &lt;/tr&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_CheckoutSuccess {
            get {
                return ResourceManager.GetString("Email_CheckoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width: 100%; overflow: hidden; background: #e6e7e8;&quot;&gt;
        ///        &lt;table style=&quot;max-width: 600px; height: 43px; margin: 0 auto; width: 100%; background: #fff; border-spacing: 0px;&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td style=&quot;width: 50%; padding-left: 43px;&quot;&gt;&lt;a href=&quot;http://dealtoday.vn&quot;&gt;
        ///                    &lt;img src=&quot;http://dealtoday.vn/asset/images/logo.png&quot; alt=&quot;dealtoday.vn&quot; /&gt;&lt;/a&gt;&lt;/td&gt;
        ///                &lt;td style=&quot;width: 50%; padding-right: 45px; text-align: right; font-family: Arial; font-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Email_CheckoutSuccess_V2 {
            get {
                return ResourceManager.GetString("Email_CheckoutSuccess_V2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam on QK da dat san golf tai Dealtoday.vn. DH {0}. Chung toi se dat san va lien he lai voi QK trong thoi gian som nhat LH: 19002065.
        /// </summary>
        internal static string Golf_ComfirmationSMS {
            get {
                return ResourceManager.GetString("Golf_ComfirmationSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;width: 100%; overflow: hidden; background: #e6e7e8;&quot;&gt;
        ///        &lt;table style=&quot;max-width: 600px; height: 43px; margin: 0 auto; width: 100%; background: #fff; border-spacing: 0px;&quot;&gt;
        ///            &lt;tr&gt;
        ///                &lt;td style=&quot;width: 50%; padding-left: 43px;&quot;&gt;&lt;a href=&quot;http://dealtoday.vn&quot;&gt;
        ///                    &lt;img src=&quot;http://dealtoday.vn/asset/images/logo.png&quot; alt=&quot;dealtoday.vn&quot; /&gt;&lt;/a&gt;&lt;/td&gt;
        ///                &lt;td style=&quot;width: 50%; padding-right: 45px; text-align: right; font-family: Arial; font-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Golf_ConfirmationEmail {
            get {
                return ResourceManager.GetString("Golf_ConfirmationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cam on Quy khach dat mua tren Dealtoday.vn. DH {0} tri gia {1} vnd dang duoc xu ly. LH: 19002065.
        /// </summary>
        internal static string SMS_CheckoutSuccess {
            get {
                return ResourceManager.GetString("SMS_CheckoutSuccess", resourceCulture);
            }
        }
    }
}
